[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist-server/db/seed.js && NODE_ENV=production node dist-server/index.js"
